const CREATE_POST = "post:CREATE_POST";
const UPDATE_POST = "post:UPDATE_POST";
const DELETE_POST = "post:DELETE_POST";
const LIKE_POST = "post:LIKE_POST";
const GET_POST_BY_ID = "post:GET_POST_BY_ID";
const TIMELINE_POSTS = "post:TIMELINE_POSTS";
const POST_COMMENT = "post:POST_COMMENT";
module.exports = {
    CREATE_POST,
    UPDATE_POST,
    DELETE_POST,
    LIKE_POST,
    GET_POST_BY_ID,
    TIMELINE_POSTS,
    POST_COMMENT
}